### ISSUE TITLE
Rummaging mod

### ISSUE THREAD

**Issue by Entity-y** [I-am-Erk/CDDA-Tilesets#1075]
This mod alters furniture container sprites once they have been opened, often changing the sprite to something else. 

Furniture container sprites should have opened versions of it, or default to using identical sprites.

**Comment by int-ua** [comment]
Is it a feature request? Please post it upstream at https://github.com/CleverRaven/Cataclysm-DDA/issues/new/choose I like the idea but AFAIU it's impossible to implement just in a tileset so it should be first implemented in the game so it's not a proper place to discuss it.
