### ISSUE TITLE
Please add a tile for t_floor_primitive

### ISSUE THREAD

**Issue by hexagonrecursion** [I-am-Erk/CDDA-Tilesets#1157]
This tile is used by faction camps

![DeepinScreenshot_select-area_20220104221454](https://user-images.githubusercontent.com/52621858/148111768-04aae6f8-2e06-4b05-8296-3b1d65393b87.png)

**Comment by NetSysFire** [comment]
I wonder if a workaround would be a `looks_like` for that specific file "upstream" in the cdda repo. I would perhaps choose dirt as the `looks_like`.

**Comment by hoasd1** [comment]
I covered this one in #1421 also it got merged in the recent experimental versions of CDDA.

**Comment by I-am-Erk** [comment]
this definitely should have a looks_like in CDDA though.

**Comment by NetSysFire** [comment]
I just filed a PR that would add looks_like to that and another couple of things.

**Comment by Travia21** [comment]
[#59018](https://github.com/CleverRaven/Cataclysm-DDA/pull/59018)

NetSysFire's PR was merged, this issue can probably be closed.
