### ISSUE TITLE
Black background on memory

### ISSUE THREAD

**Issue by linonetwo** [I-am-Erk/CDDA-Tilesets#1230]
![截屏2022-02-08 21 34 04](https://user-images.githubusercontent.com/3746270/152997632-a131d0a6-b103-4195-8617-4c4eabe38b7c.png)
![截屏2022-02-08 21 34 20](https://user-images.githubusercontent.com/3746270/152997687-97578819-6560-4ba4-9f86-efead2cf5da1.png)

It gets black background, which is misleading...I always thought that is a wall, but actually a flower.

**Comment by Fris0uman** [comment]
It's a game engine thing, I think it does that with every furnitures

**Comment by linonetwo** [comment]
OK, I think I should move this issue to game's repo.
