### ISSUE TITLE
The blood covers other items

### ISSUE THREAD

**Issue by Voidext** [I-am-Erk/CDDA-Tilesets#133]
It seems that the blood covers other items and it is hard for me to find them and pick them up. It it a bug? Is there a way to fix it?
![image](https://user-images.githubusercontent.com/41903646/81770792-241b5e00-9496-11ea-83d8-8ed0a8dbf649.png)

**Comment by barsoosayque** [comment]
Hmm. I don't see any items behind blood fields. Also, from the code, it seems like it's simply impossible since all items are drawn after field (blood, in this case) is drawn.
Did I miss something on your screenshot ? Can you provide more context for it ?

**Comment by Voidext** [comment]
I was examine the blood left to me. There are a lot of items on the ground, like clothes, corpse, etc. However, there are not shown on the graph.

Btw, I fixed by adding an "unknown" object to the tileset ultica.

**Comment by barsoosayque** [comment]
Ok, I was trying to reproduce that, but it's all ok for me (I even selected chinese language). What version of the game are you using and what Ultica build ?

<details>
<summary>My test screenshot</summary>

![image](https://user-images.githubusercontent.com/33784900/82017454-65398b00-96ad-11ea-8029-bd5f9e23c967.png)

</details>

**Comment by Voidext** [comment]
The version is 0.E stable. Personally I don't know why that happened (maybe by chance?). I tried both the Ultica beta and the one on github. In both of them the items under the blood will not be shown, like this.
![image](https://user-images.githubusercontent.com/41903646/82039619-1ca4b200-965a-11ea-9002-a35709cdb602.png)
![image](https://user-images.githubusercontent.com/41903646/82039653-29290a80-965a-11ea-9cc1-c9eaf55b1bac.png)
This is my save file.
[阿拉曼斯.zip](https://github.com/I-am-Erk/CDDA-Tilesets/files/4633724/default.zip)
Thank you for your concerns.

**Comment by barsoosayque** [comment]
Oh, I forgot to say that I tested your save, and I reproduced the issue. Still, no clue why, because `fd_blood` is defined in UltiCa like in every other tileset.

**Comment by int-ua** [comment]
I cannot reproduce it, please reopen if it's still happening on latest experimental.
