### ISSUE TITLE
Retrodays/Neodays overlay status icons

### ISSUE THREAD

**Issue by MichaelMackus** [I-am-Erk/CDDA-Tilesets#1363]
It would be quite nice to have status icons for things like bleed, grabbed, etc. in neodays (and maybe retrodays). Is this something that would be of interest or is this too far from the intent of the tilesets? I feel myself using BrownLikeBears a lot lately because of the status indicators, but I actually prefer the look & feel of Retrodays. 

If there's some interest when I find some time I can try to work on a PR for this. Just thinking something simple like BrownLikeBears has for crouching, running, grabbed, bleeding, etc.... if that's too much maybe even just a crouching/running icon would be good to have.

**Comment by Golfavel** [comment]
There is a graphical mod packed in with the game that actually adds such icons, which can be enabled during world creation; although I'm unsure as to why they are done via a mod instead of in the packs directly.

**Comment by Fris0uman** [comment]
Yep, no problem with adding it as default into NeoDays

**Comment by MichaelMackus** [comment]
I did find a mod that enabled "hostile_sees_player" overlay @Golfavel but couldn't find another that did the crouching/running icons. I think that would be a satisfactory solution for sure, having it as a mod is a bit odd but enables an "optional" graphics feature like this. Adding it as a core part of neodays would make a good deal of sense but I wonder if enabling said mod would conflict with those sprites in the theme (if they ever differentiate at least).

**Comment by Golfavel** [comment]
That mod (assuming it's ``sees_player_retro``, which is packed with the game builds) also includes icons for running, crouching, proning, bleeding, and light emission. It does seem to have a bug where it won't work properly if it isn't loaded first (i.e., playing a world without it, then entering a world with it, will cause the additions to not show)
I may merge it into NeoDays by when/if I get time and no one beats me to it.
