### ISSUE TITLE
No overmap path indicators for autotravel with Surveyor's Map tileset

### ISSUE THREAD

**Issue by mlange-42** [I-am-Erk/CDDA-Tilesets#1373]
### Describe the bug

When auto-travelling while using the Surveyor's Map tileset for the overmap, the path of travel is not visible.

### Steps to reproduce

1. Set overmap tileset to SurveyorsMap
2. Open the overmap (`m`)
3. Try to auto-travel somewhere (`W`)
4. See that you see no path indicators

### Expected behavior

After pressing `W` the first time, the path to travel should be indicated

### Screenshots

![grafik](https://user-images.githubusercontent.com/44003176/171853574-aea81491-cd72-4690-a313-cd57f8fa7514.png)

### Versions and configuration

- OS: MS Windows 10
- Game version: Build 2022-05-25-0655
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: dda

----

Originally posted in [CleverRaven/Cataclysm-DDA](https://github.com/CleverRaven/Cataclysm-DDA): https://github.com/CleverRaven/Cataclysm-DDA/issues/58111

**Comment by Fris0uman** [comment]
Fixed by https://github.com/I-am-Erk/CDDA-Tilesets/pull/1327
