### ISSUE TITLE
[RetroDays overmap] Isherwoods specials are missing tiles

### ISSUE THREAD

**Issue by NetSysFire** [I-am-Erk/CDDA-Tilesets#1433]
![image](https://user-images.githubusercontent.com/59517351/177013067-7b3d2e72-0175-462e-ac8a-b907eabc6399.png)

I am unfortunately not aware of `looks_like` existing for overmap terrain, so it would be great if the special forests, fields and rural roads could get  displayed like their normal variants. This should be relatively easy since it is just aliasing tiles since there is no reason to not re-use the existing textures of the normal variant.

**Comment by Fris0uman** [comment]
looks_like does exist for overmap terrain, we just need someone to set them up
