### ISSUE TITLE
Ultica Skin

### ISSUE THREAD

**Issue by Grentari** [I-am-Erk/CDDA-Tilesets#1478]
The default character color is bronze (just use the debug) with the same MSX. But in Ultica it is light brown (I don't think it corresponds to lore). Also, I don't think your "light" can be called light.

**Comment by Fris0uman** [comment]
Default skin can be whatever color, this is not a bug

**Comment by Grentari** [comment]
At the same time, other sets use only bronze. REALISTICALLY, YOU DON'T UNDERSTAND.
