### ISSUE TITLE
Out of beta Final Push

### ISSUE THREAD

**Issue by I-am-Erk** [I-am-Erk/CDDA-Tilesets#151]
I plan to remove the Beta tag from Ultica shortly, and would like to make a final push to complete certain easy fix annoying sprites before getting there. Vehicle parts for cars and maybe bikes are already included automatically.

 Here are some candidates. I don't expect to cover everything.

- [x] Bulletin board
- [x] Sound indicator
- [x] t_pit has a glitch where a `0` appears on top, fix that
- [x] t_pit_spiked
- [ ] desaturate carpet sprites and add edging as has been done for purple and green carpet
- [x] at least one fish sprite (trout) (wapcaplet)
- [x] bridge ramps (and maybe guard rails, though that could be looks_like)
- [x] Add multitile to pavement to get a smooth edge
- [x] Add multitile (at least a simple one) to gravel and moss (barsoosayque)
- [x] Add at least one spider sprite (wapcaplet)
- [ ] Make sure all starting profession clothes have overlays
- [x] add aliases for book sprites so they don't show as fillers
- [x] At least a filler tile for canvas walls and doors
- [x] at least basic roof art

Ensure all starting zombies have sprites:
 - [x] Feral humans
 - [x] zapper
 - [x] Biohazard
 - [x] Firefighter
 - [x] Technician
 - [x] SWAT
 - [x] cop dog
 - [x] survivor
 - [x] beekeeper

vehicle parts:
 - [ ] rotations for HD and XL vehicle panels
 - [ ] vehicle exterior tanks
 - [ ] vehicle hatches

We have been unhappy with our quest for a bounty system so far, but informally I'd like to offer a token $2 USD bounty for every:
- monster sprite
- tree graphic

I don't have to draw before Full Release. In order to collect the bounty you must:
- include source files (xcf, kra, etc)
- follow our sprite style guidelines
- have final version approved by me or barsoosayque

For now I have a soft cap of around $100 before I start rethinking this bounty.

**Comment by barsoosayque** [comment]
Dibs on gravel and moss (I already have them in my personal todo list, along with sand and stone). And probably other terrain fixes listed here since they kind of included in my quest of normalizing the tiles.

**Comment by I-am-Erk** [comment]
I'll probably fix pavement myself.

**Comment by wapcaplet** [comment]
I will work on some fish, spiders, and books.

**Comment by int-ua** [comment]
* [ ] sound indicator

**Comment by wiki-me** [comment]
> We have been unhappy with our quest for a bounty system so far

I saw you used issuehunt (which is proprietary), may i suggest using [rysolv](https://github.com/rysolv/rysolv)?, unlike issuehunt it's open source and unlike bountysource it can show the most funded issues for a project (which can act as a indicator or a form of feedback to what people think is the most valuable task).
