### ISSUE TITLE
Active bionics do not appear

### ISSUE THREAD

**Issue by Golfavel** [I-am-Erk/CDDA-Tilesets#1541]
Sprites for active bionics such as active night or thermal vision do not display, likely due to a change upstream.
This affects MSXotto+, RetroDays, and NeoDays due to them having sprites for such instances.

**Comment by Fris0uman** [comment]
should probably report it in the game repo then

**Comment by Golfavel** [comment]
Whoops, misclick.
I'm not sure if it's a bug and these item states just don't work at all, or if the id format for calling them changed.
