### ISSUE TITLE
[BrownLikeBears] sprites of things below pc (on different z-levels) are too bright to play comfortably in the dark

### ISSUE THREAD

**Issue by Xerathe** [I-am-Erk/CDDA-Tilesets#1763]
See the screenshots first and compare.

BrownLikeBears
![2022-12-26 14_47_42-000692](https://user-images.githubusercontent.com/111675193/209546062-288c8512-37a5-452c-9969-52cf271d4cec.png)

Smashbutton_iso
![2022-12-26 14_47_03-000691](https://user-images.githubusercontent.com/111675193/209546121-634db1d7-2a00-4060-922f-57edb5fc3278.png)

My problem is that even with the brightness option on my monitor set to 0 (I never put it on more than 10 anyway) it gets really uncomfortable to play the game in dark environments (e.g. for atmosphere purposes, especially with a good soundpack, like Otopack (not an ad))

My suggestion or request would be to either pick a darker hue or make it black like in Smashbuttons' or UltiCa's (or some others') tilesets.

**Comment by Fris0uman** [comment]
The solution is to replace the t_open_air.png (with some numbers around in the name) image with a transparent sprite, delete the json of the same name and rename the png to actually be t_open_air.png
I don't have a computer to do it right now, so if no one does it before it will have to wait for me to get to a computer in a few weeks
