### ISSUE TITLE
Mushroom

### ISSUE THREAD

**Issue by sdgoihew** [I-am-Erk/CDDA-Tilesets#1863]
Don' know if you need this, or appropriate. Here's blank mushroom of hopefully human size for ?magiclysm? (Funnelcap?) or whatever.

512px ![mushroom2_stable_diffusion_512](https://user-images.githubusercontent.com/115432842/220167068-d2a8315c-8705-42df-a0c0-c5d427737980.png)
64px ![mushroom2_stable_diffusion_64](https://user-images.githubusercontent.com/115432842/220167061-d54f8cfd-f0ef-4865-846e-3c952e58cfe5.png)
32px ![mushroom2_stable_diffusion_32](https://user-images.githubusercontent.com/115432842/220167066-632484d5-c53d-45e5-9079-0acad86ad027.png)

**Comment by Fris0uman** [comment]
Use the discord https://discord.gg/VVv7AcS or make a proper pull request to submit sprites.
