### ISSUE TITLE
[MSX] Lily's sprite includes water despite not being a water plant

### ISSUE THREAD

**Issue by Karol1223** [I-am-Erk/CDDA-Tilesets#1921]
As the title suggests. The lily was likely mistaken to be connected to lilypads during the drawing and now comes with its own water... despite the fact that this is a fully terrestrial plant that spawns solely on land.

**Comment by Fris0uman** [comment]
![image](https://user-images.githubusercontent.com/41293484/227708751-c148695f-7465-456b-8635-8493cd65bb68.png)
 True: lily on the right here
