### ISSUE TITLE
Certain vehicles have wrong tile art.

### ISSUE THREAD

**Issue by UndeadMoose** [I-am-Erk/CDDA-Tilesets#200]
After playing Ultica for these past few days I have noticed certain vehicles have wrong tile art on certain parts.

Ill list the vehicles and the screenshots of the vehicles I have noticed that have the wrong tile art.

 - The ambulance has two different looking doors.
![Screenshot (2844)](https://user-images.githubusercontent.com/56947231/90945581-a5ed3100-e460-11ea-92b1-45a5e52ae883.png)

- This SUV has doors that are oriented wrong.

![Screenshot (2846)](https://user-images.githubusercontent.com/56947231/90945674-49d6dc80-e461-11ea-84c5-70271a599076.png)

- The Atomic Car in Aftershock has windshields that are not connected neither are the boards
![Screenshot (2851)](https://user-images.githubusercontent.com/56947231/90945864-9838ab00-e462-11ea-9066-202e13a2c325.png)

- The Humvee not only has doors that are oriented wrong it also looks like the heavy duty board doesn't connect to the door quite right.
![Screenshot (2853)](https://user-images.githubusercontent.com/56947231/90945904-e9489f00-e462-11ea-8981-32ade5e1b0bf.png)

- The Superbike has missing art (or art not displaying?) 
![Screenshot (2856)](https://user-images.githubusercontent.com/56947231/90945951-5fe59c80-e463-11ea-921b-292030469a01.png)

- The Car just like the Ambulance also has two different pieces for the doors
![Screenshot (2860)](https://user-images.githubusercontent.com/56947231/90945980-acc97300-e463-11ea-8a8f-5bc714d13973.png)

- The Low-End Cube Van has doors oriented the wrong way
![Screenshot (2863)](https://user-images.githubusercontent.com/56947231/90945999-e1d5c580-e463-11ea-830b-81eb33829097.png)

- Not sure if there isn't art or it isn't displaying the sliding door but this is what the hippie van looks like
![Screenshot (2865)](https://user-images.githubusercontent.com/56947231/90946027-0a5dbf80-e464-11ea-8e95-8052ba6ecbf7.png)

- The Fire Truck's stow boards don't connect quite right to the windshields.
![Screenshot (2867)](https://user-images.githubusercontent.com/56947231/90946058-501a8800-e464-11ea-9627-20561905aa87.png)

- These are just a few to name. 

1. The more I play I discover at certain angles the door tile art is oriented wrong though only on certain vehicles. 
- For the cars displaying the wrong door tile art it happens randomly.

**Comment by int-ua** [comment]
@UndeadMoose can you please test again? Some of these were fixed, probably not all.
