### ISSUE TITLE
[ChibiUltica] Large monsters have right-most square clipped.

### ISSUE THREAD

**Issue by Zarhon** [I-am-Erk/CDDA-Tilesets#2022]
See screenshots. Applies to both living and dead creatures.
<img width="244" alt="Screenshot_2" src="https://github.com/I-am-Erk/CDDA-Tilesets/assets/39234303/5dbe6cf8-1db6-4cca-9f03-09419e6b02f2">
<img width="192" alt="Screenshot_3" src="https://github.com/I-am-Erk/CDDA-Tilesets/assets/39234303/9161f00e-e074-497a-ac91-91d98b0604fb">
<img width="395" alt="Screenshot_4" src="https://github.com/I-am-Erk/CDDA-Tilesets/assets/39234303/2a9e1eb1-e0f6-4cd1-96aa-dbd15df17495">

**Comment by Fris0uman** [comment]
this looks like a problem on the game side, like if the draw order of sprites had changed

**Comment by Fris0uman** [comment]
should be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/66332
