### ISSUE TITLE
MSXOtto+ & Ultica/Chibi Ultica lack LEAVES2 & 3 sprites, others

### ISSUE THREAD

**Issue by fairyarmadillo** [I-am-Erk/CDDA-Tilesets#2256]
LEAVES is a mutation with 3 levels and (now) 3 variant forms, but both Ultica and MSXOtto+ only have sprites for LEAVES1's spring/summer form. LEAVES1_WINTER needs a sprite. Per its description this should just be a blonde/brown looking version of LEAVES1

Additionally, MSXOtto has a weird messed up sprite for CHLOROMORPH that should probably just be removed. It's layered incorrectly and whatever it's depicting no longer matches what the mutation does, which is to just make you generally more planty.

There are also variants for many mutations which should probably still display the same sprite. These include all the CHITIN molt variants, and the new URSINE_FUR_SUMMER and LUPINE_FUR_SUMMER. If you want to add some variety just for the sake of it, the CHITIN molted variants other than CHITIN_CARAPACE could be a much lighter shade.

LEAVES2, LEAVES3, LEAVES2_FALL, and LEAVES3_FALL need sprites. Per their description these add progressively more leaves to the player's head and also their arms. The arm sprites may be tricky to depict, but as it's mechanically relevant I suggest at least putting some patterning on the character's arm which can be covered by clothing (which is how the mutation works). The fall versions are just the same leaves but autumn colored. LEAVES3_FALL is described as being especially pretty and has less ugliness than the others as a result.

ROSEBUDS also has 2 new variants. Regular ROSEBUDS is budding flowers, ROSEBUDS is big especially beautiful ones, and ROSEBUDS_FALL is a few little fruits growing from stems on the character's head, which are described as looking sort of like plums.

I would simply do this myself, but I have tried and I cannot for the life of me figure out how to get the game to actually display new sprites. Thank you to whoever looks at this and sorry for creating all this extra work. 😅

**Comment by Psithief** [comment]
All of the extra leaf mutations got reverted in https://github.com/CleverRaven/Cataclysm-DDA/commit/6b63aad974dd6146a999a303bcd084baf213199d

**Comment by Fris0uman** [comment]
Alright, closing then
