### ISSUE TITLE
Errant pixel in Ultica when ovens are facing sideways

### ISSUE THREAD

**Issue by Karlington2** [I-am-Erk/CDDA-Tilesets#2327]
When ovens are facing sideways in Ultica, an errant pixel appears:

![m8sl32kwurpc1](https://github.com/I-am-Erk/CDDA-Tilesets/assets/80838615/759d3c08-e89d-426f-9474-3217c0f4251a)

**Comment by hoasd1** [comment]
Confirmed!
All rotations expect South[S] rotation have stray\out-of-place pixels.

**Comment by Fris0uman** [comment]
fixed by  #2337
