### ISSUE TITLE
(UltiCa)Corrosive zombie sprite may be too small for "Large" size

### ISSUE THREAD

**Issue by acepleiades** [I-am-Erk/CDDA-Tilesets#237]
The corrosive zombie sprite appears human-sized, while it is a "Large" monster. They are supposed to be bigger than brutes, which are "Medium" monsters.
![mon_zombie_corrosive](https://user-images.githubusercontent.com/69649956/91759958-e65b5600-eba8-11ea-86f8-ab45aaaa4fd5.png)
![mon_zombie_brute](https://user-images.githubusercontent.com/69649956/91760088-1c003f00-eba9-11ea-9fe5-f39a320b4506.png)

**Comment by I-am-Erk** [comment]
Could probably just beef those legs up and make it a bit taller.

**Comment by acepleiades** [comment]
![mon_zombie_corrosive](https://user-images.githubusercontent.com/69649956/103179327-998f3f80-4869-11eb-8bad-63b9d1ea1f10.png)
I changed it
