### ISSUE TITLE
Adding mods in the mod file results in an error message 

### ISSUE THREAD

**Issue by SentientRobotMKI** [I-am-Erk/CDDA-Tilesets#2420]
I made a personal mod that fits the game's requirements to recognize it as a mod.

One of the basic requirements for the game to recognize a mod is the modinfo.json, My mod has this, but when I try to load it in the game it gives me an error message.

Here is the error code:
 DEBUG    : Failed to read from "/storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/data/mods/Farlands/modinfo.json": opening file failed

 FUNCTION : std::optional<std::string> read_whole_file(const fs::path &)
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/cata_utility.cpp
 LINE     : 552
 VERSION  : cdda-experimental-2024-06-19-0447 551e1b5

![Screenshot_20240621-233320.png](https://github.com/I-am-Erk/CDDA-Tilesets/assets/173482025/cfee8650-e61f-48d6-b308-6631cab85a41)

Since I am new in modding with barely any knowledge in coding, it could be because that I did something wrong. The mod I made isn't that intricate either.

What I did was:
1.Create a modinfo JSON file on android
2.Put it in a folder located in the mods folder
3.Load the game for results

I did this on an Android 13
cdda-experimental-2024-06-19-0447

**Comment by hoasd1** [comment]
It's better to ask in **CDDA Development Discord** server as you could get help faster than here >.>
**There's invite link in Cataclysm-DDA Github page in Community named Official Discord**
