### ISSUE TITLE
proposal for retrodays+

### ISSUE THREAD

**Issue by captnblood** [I-am-Erk/CDDA-Tilesets#244]
i would like to discuss about retrodays+, propose some ideas, discuss it's future direction and/or eventually branch from it into a new tileset.

the idea that i would like to discuss is this one:
retrodays+ just like retrodays uses 10x10. it looks nice but the 10x10 is somewhat a bit limiting.
i think by upgrading to 16x16 instead would be a better fit for retrodays+
it would allow a little bit more creativity and tile customisation while in the same time keeping it true and close to the original (retrodays) in look and feeling. and be just that: a retrodays with small improvement here and there. 

when i created retrodays+ at first people seemed kind of against it. i received lukewarm response, 
- many "meh".. 
- a few "that is not needed / not wanted / it shouldn't exist, put it in the trashcan". 
- many seemingly authoritative advices that i should name it this or that instead.

and things like that. now i discover people actualy like retrodays+ and want to protect it from me, the person who made it, despite the lukewarm response and naysaying in the beginning. well it's nice to see that my idea for retrodays+ finally catched on and that my original idea is getting appreciated.

now i have some additional ideas, and improvements to propose again, for retrodays+, and folks are starting to say the same kind of things as before. "why?", "oh no, don't do this!", "this is bad..", "make a new tileset instead", "call it this or that" .. and so on...

the idea with retrodays+ was to have something that generaly felt similar to retrodays, but with improvements. like transparency and many other little changes that other viewed as too destructive for the original tileset (retrodays). now i propose we go to 16x16  instead of 10x10. i think this should be a fitting idea for "retrodays+". i have made the scale changes myself (80% done, i'll link what i've done so far at the end of this post). 

why 16x16 ? because it's close to 10x10 but the extra pixel space per tile will allow many little improvement everywhere while also still staying close to original in style and feels.  
i also propose to put faces on the characters and also allow clothing overlay. the 10x10 size wasn't permiting much in this area (overlays and faces) but 16x16 will allows that.
please consider the following:
![preview3](https://user-images.githubusercontent.com/64192330/92144686-5bcc5e00-ee17-11ea-9c47-0cdb0bf3f648.png)

the  idea is that by going 16x16, for furniture, and keeping objects to their original size, centered, we can display in game, a furniture that contain an object, and that could be shown. whereas previously the object would mostly shadow the furniture. here i show a fridge that ontain a bottle. we can still see the fridge behind the the bottle. so most retrodays objects will be kept at 10x10, centered in a transparent 16x16 tile. in turn, most furniture will instead use the full extent of the 16x16 additional space gain.

also as you can see, going 16x16 could allow us some nice characters customisation whereas before it would be more tricky to do. 

the first row of that image above, contains tiles for buildings interiors floors and also new road and sidewalk pavement tiles that i think look much better than in current retrodays and retrodays+. i will attach the work i've done so far. if you want to test it, while it's a W.I.P, it already works and looks nice.

so what is your input on this, should we make yet another retrodays based standalone, separate new tileset, or could we focus on migrating retrodays+ to 16x16 for a future release ?

this file is tar.gz archive, renamed to allow upload to github. ("tar -xzvf retroplus16.zip" to extract)
[retroplus16.zip](https://github.com/I-am-Erk/CDDA-Tilesets/files/5170143/retroplus16.zip)

**Comment by Wokko1** [comment]
> it would allow a little bit more creativity and tile customisation while in the same time keeping it true and close to the original (retrodays) in look and feeling. and be just that: a retrodays with small improvement here and there.

The thing is, what you are proposing is not "small improvements". Retrodays+ did not have such problems because making backgrounds transparent was relatively a small change. Redrawing half the tileset (creatures, furniture) is too big of a change to call it "small improvements".
Of course 16 pixels would allow for more details to fit, but it would drift away from the original design that's all about simplicity.

> now i discover people actualy like retrodays+ and want to protect it from me, the person who made it

I think that's because you are trying to basically nuke the entire tileset and substitute it with a different one based on RD+, instead of letting people choose what they like more.
I'd say it would be better to make it a separate tileset rather than making significant changes to the existing one.

**Comment by captnblood** [comment]
@Wokko1 
when i made retroplus i also changed many tiles. one striking example are floors, but not only, i did change quite a bit of things everywhere. the very idea behind the creation of retroplus was to improve from original, while keeping it generaly similar in feeling. namely old school blocky pixel art, retaining most of the design while allowing improvement a bit everywhere. and i did just that. and this new change i'm proposing here now would still be the same. end result would make it 80 to 90% retrodays look-alike. with goodies. upgrading to 16x16 seems fitting of the retroplus idea. same but a little bit better. you should try it, you'll see that what i have made this time fits in this category and that it looks and feels like a retrodays with the "+" added. this kind of things was the very reason this tileset was made for.

**Comment by Wokko1** [comment]
Maybe the people who are against it are not the same people who like it now?
Anyway, you missed the point, what you are proposing is not "80-90% look-alike".
If you are really adamant about it, make it a separate tileset please. Your sprites are too different (and in my opinion, lose to the original retrodays sprites).

**Comment by captnblood** [comment]
have you even tried it to say it is not looking similar ? i bet you haven't.
the situation is a bit like, steve jobs getting kicked out of apple.
i mean having to plead and justify to modify my own tileset, that's ridiculous ;)
