### ISSUE TITLE
(UltiCa) Geese still displays duck sprite

### ISSUE THREAD

**Issue by acepleiades** [I-am-Erk/CDDA-Tilesets#249]
![geese](https://user-images.githubusercontent.com/69649956/92336396-77816f80-f076-11ea-85be-cd928a7bee67.png)
Geese now have their own sprite but are still using their look-alike duck sprite.

**Comment by int-ua** [comment]
Are they `mon_goose_canadian_chick`?

**Comment by int-ua** [comment]
@acepleiades is it still relevant?

**Comment by int-ua** [comment]
Cannot reproduce, please reopen if necessary
