### ISSUE TITLE
Add Mod Support To Ultica

### ISSUE THREAD

**Issue by Theawesomeboophis** [I-am-Erk/CDDA-Tilesets#294]
This is a request From my issue https://github.com/CleverRaven/Cataclysm-DDA/issues/45147 to add minor mod support to Ultica.

**Comment by I-am-Erk** [comment]
If you would like to contribute your art you're welcome to. Otherwise, mod supports await someone to draw them.

**Comment by Theawesomeboophis** [comment]
I am not good with spriting, I have also submitted this request to the mod authors as it seemed better suited there.
