### ISSUE TITLE
ChibiUltica Unknown sprite showing for variuous, and other. (old version mixup)

### ISSUE THREAD

**Issue by xerenogan** [I-am-Erk/CDDA-Tilesets#353]
# Initial Symptoms
The unknown tile symbol is used (ChibiUltica tileset) for the examine reticle when e[x]amining, when [V]iewing, and whenever there is a stack of items.

# List of known problems so far.
-Unknown tile showing for aiming reticule(missing on spritesheet).
-Unknown tile showing for e[x]amine and [V]iewing reticule(missing on spritesheet).
-Missing item stack overlay.
-Regression to before pointed horn fix.
    (here is the sprite just in case)
![overlay_mutation_HORNS_POINTED(fixed)](https://user-images.githubusercontent.com/75096026/102544997-a51d8200-4083-11eb-8497-d5b8430c57f8.png)

**Comment by xerenogan** [comment]
Looks like the reason the targeting reticle used for examining and such is showing unknown could be because it's missing from the sheet. There's a blank where it should be.

**Comment by Fris0uman** [comment]
closed by  CleverRaven/Cataclysm-DDA#46113
