### ISSUE TITLE
How to get iso version?

### ISSUE THREAD

**Issue by linonetwo** [I-am-Erk/CDDA-Tilesets#366]
Can I download the iso (3D) version of ultica?

**Comment by int-ua** [comment]
AFAIK it was a one-time experimental automated conversion of the state at that moment. You could try composing it yourself https://i-am-erk.github.io/CDDA-Tilesets/#building

**Comment by I-am-Erk** [comment]
Presently it would require making it. I played around with it for a bit but it'll need a lot more artwork for the terrain to be usable.
