### ISSUE TITLE
Chair rotates wrongly when lined up like this

### ISSUE THREAD

**Issue by acepleiades** [I-am-Erk/CDDA-Tilesets#375]
![rotateswrongly](https://user-images.githubusercontent.com/69649956/103141439-19cf6c80-46d3-11eb-8258-bb1c084c84bd.png)
We should look into doing something about this eventually

**Comment by int-ua** [comment]
Are you sure it's not an upstream CDDA issue?

**Comment by int-ua** [comment]
I may be wrong but this looks like an upstream issue because chairs (and fridges) affect each other's rotations when armchairs don't with seemingly identical configuration.

**Comment by acepleiades** [comment]
> Are you sure it's not an upstream CDDA issue?

I think it is

**Comment by int-ua** [comment]
Please file an upstream issue, I don't have much time to spare today.

The rotation is determined by https://github.com/CleverRaven/Cataclysm-DDA/blob/41708d329c80b0cbbd10ad1d6426464ebac7ea65/src/cata_tiles.cpp#L3703

**Comment by acepleiades** [comment]
Every furniture with rotations affect each other in this way:
![rotationbug1](https://user-images.githubusercontent.com/69649956/105567934-8c545c00-5d14-11eb-9fc4-6f5d7956d577.png)
![rotationbug2](https://user-images.githubusercontent.com/69649956/105567947-9e35ff00-5d14-11eb-8434-e6625d73b3ef.png)

When they're adjacent, they face each other. Something is making them face each other when they shouldn't. I can't make heads or tails of the code.

**Comment by int-ua** [comment]
Should be fixed by https://github.com/CleverRaven/Cataclysm-DDA/pull/47157
