### ISSUE TITLE
(UltiCa) Mound of dirt displays old dirt bg and could use seasonal variants

### ISSUE THREAD

**Issue by acepleiades** [I-am-Erk/CDDA-Tilesets#377]
![mounddirt](https://user-images.githubusercontent.com/69649956/103141503-cf9abb00-46d3-11eb-8284-746c6b88b2db.png)
"Mound of dirt" displays old dirt background and could use seasonal variants

**Comment by int-ua** [comment]
Please update your Ultica, I've added winter variant a couple of releases ago. Yes, the CDDA repo lags behind. I'll try to make a PR soon.

**Comment by int-ua** [comment]
![screenshot](https://user-images.githubusercontent.com/1585431/103141866-5c10a200-4703-11eb-8608-ec36e8a93ac7.png)

**Comment by int-ua** [comment]
oh, wait, you mean other seasons?

**Comment by acepleiades** [comment]
You did an amazing job at winter, it's looking great now
But yeah other seasons still have this problem unfortunately

**Comment by int-ua** [comment]
Mount of dirt and pits need to get rid of the built-in dirt background for #390 to work
