### ISSUE TITLE
Trees are not displaying their shadows correctly

### ISSUE THREAD

**Issue by acepleiades** [I-am-Erk/CDDA-Tilesets#383]
![tree shadows](https://user-images.githubusercontent.com/69649956/103161851-00a7e800-47c7-11eb-8c97-268e03f86ea8.png)
and it looks real weird. I don't know why this happens, their shadows aren't a separate sprite. It's the same sprite, and parts of the tree reach over to the tiles where shadows don't appear.

**Comment by int-ua** [comment]
BTW, a lot of tree shadows are not at 45° angle, they need updating anyway.

**Comment by int-ua** [comment]
This can be workarounded by "moving" sun to the right side: mirrorring **most** of the sprites. Except monsters and what else?

**Comment by acepleiades** [comment]
Mirroring would be a quick and dirty solution. Ideally we would need a new layer for sprites that suffer from this problem. Currently, it's only trees (and then horde indicators for graphical overmap when that comes out). Esotericist and Erk want to make a new layer with a proper name, but I don't think that would be necessary. I think a a "tree" layer for trees exclusively would fix this problem.

**Comment by int-ua** [comment]
Why dirty? If you mirror only trees - yes, that would present inconsistency. But if we mirror everything and the light source / sun will be on the right, will there be anything dirty about it?

**Comment by int-ua** [comment]
```sh
find . -regex "\./pngs_.*_[0-9][0-9]x[0-9][0-9]/.*\.png" -not -regex ".*/vehicles?/.*" -not -regex ".*/monsters?/.*" -not -regex ".*/overlay/.*" -exec mogrify -flop {} \;
```
The biggest problem right now are the multitile sprites. They require proper renaming instead of simple mirroring.

**Comment by int-ua** [comment]
Upstream discussion https://github.com/CleverRaven/Cataclysm-DDA/issues/46534

**Comment by int-ua** [comment]
Mitigated in #689
