### ISSUE TITLE
Mismatched sprite for quad-glazed window with open curtains

### ISSUE THREAD

**Issue by AkkoRishtar** [I-am-Erk/CDDA-Tilesets#520]
More specifically, "t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed" looks like "t_reinforced_quadruple_pane_glass_open". 
Changing the tileset fixes the issue.

My damn luck, all other windows are fine (I checked), only the one I decided to build is mismatched.

**Comment by int-ua** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/data/json/furniture_and_terrain/terrain-windows.json#L2580

* `t_reinforced_quadruple_pane_glass_with_curtain` has both shutters and curtain closed,
* `t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed` has curtain open but shutters closed
* `t_reinforced_quadruple_pane_glass_with_curtain_open` has both curtain and shutters open

Did I describe them correctly?

**Comment by AkkoRishtar** [comment]
> https://github.com/CleverRaven/Cataclysm-DDA/blob/cbcfab179d4e7e7f715e21d44816d1bee1132868/data/json/furniture_and_terrain/terrain-windows.json#L2580
> 
> * `t_reinforced_quadruple_pane_glass_with_curtain` has both shutters and curtain closed,
> * `t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed` has curtain open but shutters closed
> * `t_reinforced_quadruple_pane_glass_with_curtain_open` has both curtain and shutters open
> 
> Did I describe them correctly?

That's what should be, but in actuality "t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed" looks like it has shutters open with no curtain. I say "looks like" because it functions correctly, only the visuals change. 

It has the same sprite as "t_reinforced_quadruple_pane_glass_open", but they're properly recognized as separate items. I went through both normal_terrain.png and tile_config.json, but I haven't noticed anything obvious that I could fix myself. terrain_windows.json has the correct references and different tilesets show correct visuals for the window so the issue must be in the tileset, but I can't find where

**Comment by int-ua** [comment]
`t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed` is not defined in Ultica at all:
https://github.com/I-am-Erk/CDDA-Tilesets/search?q=t_reinforced_quadruple_pane_glass_with_curtain

It has `"looks_like": "t_window_domestic",` and this one is defined: https://github.com/I-am-Erk/CDDA-Tilesets/search?q=t_window_domestic

The easiest fix is to add a tile entry with `"id": "t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed"` and `fg`(+`bg`) set to however a closed window is defined. Look at https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx/UltimateCataclysm for examples.

**Comment by AkkoRishtar** [comment]
> The easiest fix is to add a tile entry with `"id": "t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed"` and `fg`(+`bg`) set to however a closed window is defined. Look at https://github.com/I-am-Erk/CDDA-Tilesets/tree/master/gfx/UltimateCataclysm for examples.

Thank you, took me a bit of time to understand it, but I changed the quad window's fg to that of the double window in tile_config.json (they're supposed to look the same anyway), and that worked.

**Comment by int-ua** [comment]
It still needs a fix in this repository. Would you mind adding your changes with a Pull Request to share your fix with all users? Or we wait until someone else will do it.

**Comment by AkkoRishtar** [comment]
It's better to wait for someone to actually fix the problem then - all I've done is modify a correct .json to use the incorrect image that happens to correspond to what I want. I didn't fix the issue, just found a workaround.

**Comment by AkkoRishtar** [comment]
I just discovered that contrary to what I said earlier, "t_reinforced_quadruple_double_pane_glass_with_curtain_open_window_closed" actually functions partially as an open window. As  in: trying to walk in from the inside properly triggers the "open" interaction, however the window can be walked through from the outside.
To me, that signifies that the problem isn't coming from the tileset, so I'll be closing this issue as this is basically "not your problem" anymore
