### ISSUE TITLE
No visuals on "Preview Route" on overmap with "Use tiles to display overmap" set to true

### ISSUE THREAD

**Issue by Fjolset** [I-am-Erk/CDDA-Tilesets#787]
There doesn't seem to be any visual preview when creating a route with "W" on the overmap when the graphics option "Use tiles to display overmap" is set to true.

On the example below I have created a route southbound, which can't be seen.

![image](https://user-images.githubusercontent.com/32506535/128537674-f8e6bd38-2b01-41de-93e7-58670db9ef16.png)

In comparison to the ASCI overmap:

![image](https://user-images.githubusercontent.com/32506535/128538410-a1e12493-7e3a-4c6a-a358-3011db8e4c15.png)

**Comment by anothersimulacrum** [comment]
Cannot reproduce with https://github.com/CleverRaven/Cataclysm-DDA/pull/50190 applied.
![image](https://user-images.githubusercontent.com/42699974/128541828-4247c270-d820-4db0-b947-03900406d29c.png)

**Comment by Fjolset** [comment]
> Cannot reproduce with [CleverRaven/Cataclysm-DDA#50190](https://github.com/CleverRaven/Cataclysm-DDA/pull/50190) applied.

Hmm, i wonder why it doesn't show for me.

I'm not running a lot of mods. These are the only one active. Could it be "More city locations" screwing with the map? 🤔

**Comment by anothersimulacrum** [comment]
There is not a build with that PR out yet, is probably the answer. If you still have this problem in a day+, there is something else going on.

**Comment by Fjolset** [comment]
Nevermind. I am stupid. I just saw the issue got merged 40 minutes ago. It fixed the issue. Closing :)
