### ISSUE TITLE
Request: Indicator for prone movement mode?

### ISSUE THREAD

**Issue by actual-nh** [I-am-Erk/CDDA-Tilesets#796]
Hi. Prone movement mode currently lacks a move indicator from tilesets, as noted in [ CleverRaven#50638](https://github.com/CleverRaven/Cataclysm-DDA/issues/50638). This is problematic in people being aware of their movement mode. Some discussion has taken place on the dev discord's #graphics-and-sound channel, but for anyone not on that I wanted to post something here. (Current thinking for ultica is making crouch one down arrow, possibly with a slight color change for visibility, and prone two down arrows with a distinctly different color.) Thanks!

**Comment by int-ua** [comment]
Fixed in #817
