### ISSUE TITLE
Missing "tile_config.json" file

### ISSUE THREAD

**Issue by DocHogan** [I-am-Erk/CDDA-Tilesets#82]
File not found in repository

**Comment by I-am-Erk** [comment]
Some context would be nice. Did you download the tileset from [Releases](https://github.com/I-am-Erk/CDDA-Tilesets/releases), or try to run the source images? I'm guessing the latter.

**Comment by DocHogan** [comment]
Yep, looks like the latter. Thanks for the link to the latest Release version. The link I followed to the project (https://github.com/I-am-Erk/CDDA-Tilesets) brought me to what I guess is the commit/pull page for the master code base. I am COMPLETELY unfamiliar with version control, GitHub or otherwise, and even now see no way to navigate to the page you linked from the page I started on

**Comment by I-am-Erk** [comment]
I should put a big link to the current release in the readme

**Comment by Anrock** [comment]
What do you do if you want to use current master?

**Comment by anothersimulacrum** [comment]
You need to use the [tileset composing script](https://github.com/CleverRaven/Cataclysm-DDA/tree/master/tools/gfx_tools).

**Comment by I-am-Erk** [comment]
And if you do, send me a copy so I can make a new release

**Comment by anothersimulacrum** [comment]
Here's one.
[Ultica.zip](https://github.com/I-am-Erk/CDDA-Tilesets/files/4035622/Ultica.zip)
