### ISSUE TITLE
animated attribute warnings on non-experimental versions

### ISSUE THREAD

**Issue by int-ua** [I-am-Erk/CDDA-Tilesets#914]
https://github.com/CleverRaven/Cataclysm-DDA/pull/51257

**Comment by wiki-me** [comment]
Until this is fixed, if i will use the tileset the warning are meaningless? i can just use it and there will be no problems?

**Comment by int-ua** [comment]
> Until this is fixed, if i will use the tileset the warning are meaningless? i can just use it and there will be no problems?

IIRC, yes

**Comment by int-ua** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/0.F-3
